GET http://localhost:3000/movies/ 

##################
GET http://localhost:3000/movies/46/

##################
POST http://localhost:3000/movies/ 

Content-Type:application/json 
{
    "directorId":6,
    "movieName":"Jurassic Parks",
    "leadActor":"Jeff Goldblum"
}

##################

PUT http://localhost:3000/movies/46/

Content-Type:application/json 
{
    "directorId":6,
    "movieName":"Jurassic Parks",
    "leadActor":"Jeff Goldblum"
}

##################
DELETE http://localhost:3000/movies/46/

#############
GET http://localhost:3000/directors/

##########
GET http://localhost:3000/directors/4/movies/